services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"


  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
       KAFKA_ADVERTISED_HOST_NAME: localhost
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#### docker exec -it kafka kafka-topics.sh --create --topic youness --bootstrap-server localhost:9092 --partitions 3 --replication-factor 1
#### docker exec -it kafka kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic youness --from-beginning



